#!/bin/bash


YRI_RUNTIME_MONITOR_CLASS=""


for f in $(dir ${COMPILER_GENERATED_OUTPUT_FOLDER_FULL_PATH}/*.hpp);
do
    YRI_INCLUDE_PATH=$(basename $f)

    RUNTIME_MONITOR_INCLUDE_CODE="${RUNTIME_MONITOR_INCLUDE_CODE}#include \"src/${YRI_INCLUDE_PATH}\"\n"

    YRI_HEADER_ENDING=".hpp"
    YRI_RUNTIME_MONITOR_CLASS="${YRI_INCLUDE_PATH%%${YRI_HEADER_ENDING}}"
    YRI_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE="an_${YRI_INCLUDE_PATH%%${YRI_HEADER_ENDING}}_instance"

    YRI_PRO_FILE_CONTENT_REPLACE="${YRI_PRO_FILE_CONTENT_REPLACE}HEADERS += \$\$files(\$\$PWD/src/${YRI_INCLUDE_PATH})\n"
    YRI_PRO_FILE_CONTENT_REPLACE="${YRI_PRO_FILE_CONTENT_REPLACE}SOURCES += \$\$files(\$\$PWD/src/${YRI_RUNTIME_MONITOR_CLASS}.cpp)\n\n"

    echo "YRI_RUNTIME_MONITOR_CLASS: ${YRI_RUNTIME_MONITOR_CLASS}"

    YRI_RUNTIME_MONITOR_INSTANTIATION_CODE="${YRI_RUNTIME_MONITOR_INSTANTIATION_CODE}${YRI_RUNTIME_MONITOR_CLASS} ${YRI_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE}(\&logger);\n\t"
    YRI_RUNTIME_MONITOR_INSTANTIATION_CODE="${YRI_RUNTIME_MONITOR_INSTANTIATION_CODE}new IYRIruntimeverificationAdaptor(\&${YRI_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE});\n\t"
    YRI_RUNTIME_MONITOR_INSTANTIATION_CODE="${YRI_RUNTIME_MONITOR_INSTANTIATION_CODE}YRI_DB_RUNTIME_VERIF_Config::user_defined_Runtime_Monitors.append(\&${YRI_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE});\n\n"
done


echo "* include code text:"
printf "${RUNTIME_MONITOR_INCLUDE_CODE}"
printf "${YRI_RUNTIME_MONITOR_INSTANTIATION_CODE}"



sed -i \
    "s|#YRI-USER-CODE-INCLUDE|${YRI_PRO_FILE_CONTENT_REPLACE}|g" \
    "yri-db-runtime-verif.pro"


sed -i \
    "s|\/\/yri-USER-RUNTIME-MONITOR-RELATED-IMPORTS|${RUNTIME_MONITOR_INCLUDE_CODE}|g" \
    "src/yri-db-runtime-verif.cpp"


sed -i \
    "s|\/\/yri-USER-RUNTIME-MONITOR-DECLARATION-INSTANTIATION|${YRI_RUNTIME_MONITOR_INSTANTIATION_CODE}|g" \
    "src/yri-db-runtime-verif.cpp"

